---
apiVersion: v1
kind: Service
metadata:
 name: mydb-service
 namespace: devproject
spec:
 ports:
 - name: mysql
   port: 3306
   targetPort: 3306
   protocol: TCP
 selector:
   apptype: db
   env: production-db