apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: datastore
 namespace: devproject
provisioner: kubernetes.io/aws-ebs
parameters:
 type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
 - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: devpvc
 namespace: devproject
spec:
 accessModes:
   - ReadWriteOnce
 storageClassName: datastore
 resources:
   requests:
     storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mysql-stateful
 namespace: devproject
spec:
 volumeClaimTemplates: #Reclaim policy: data will be re added whenever pod deleted
   - metadata:
      name: data
     spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
 replicas: 1
 serviceName: mysqlsvc
 selector:
   matchLabels:
    apptype: db
    env: dev
 template:
   metadata:
     name: dbtemp
     labels:
       apptype: db
       env: dev
   spec:
    volumes:
    - name: dbvolume
      persistentVolumeClaim:
        claimName: devpvc

    containers:
    - image: ayyadoc/event-mysql:v3
      name: db
      imagePullPolicy: Always
      ports:
      - name: mysql
        containerPort: 3306
        protocol: TCP     
      volumeMounts:
        - name: dbvolume
          mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
 name: db  # This is the db host we should use in php file
 namespace: devproject
spec:
 ports:
 - name: mysql
   port: 3306
   targetPort: 3306
   protocol: TCP
 selector:
   apptype: db
   env: dev