apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mysqlinst
 namespace: devproject
spec:
 volumeClaimTemplates: #Reclaim policy: data will be re added whenever pod deleted
   - metadata:
      name: data
     spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
 replicas: 1
 serviceName: mysqlsvc
 selector:
   matchLabels:
    apptype: db
    env: dev
 template:
   metadata:
     name: dbtemp
     labels:
       apptype: db
       env: dev
   spec:
    volumes:
    - name: dbvolume
      persistentVolumeClaim:
        claimName: devpvc

    containers:
    - image: mysql:latest
      name: dbcon
      image: ayyadoc/event-mysql:v2
      imagePullPolicy: Always
      ports:
      - name: mysql
        containerPort: 3306
        protocol: TCP     
      volumeMounts:
        - name: dbvolume
          mountPath: /var/lib/mysql
---
apiVersion: v1
kind: Service
metadata:
 name: mysqlsvc
 namespace: devproject
spec:
 ports:
 - name: mysql
   port: 3306
   targetPort: 3306
   protocol: TCP
 selector:
   apptype: db
   env: dev