apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: devproject
  labels:
    app: apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        image: ayyadoc/event-management:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: hostvol
            mountPath: /var/www/html/
      volumes:
         - name: hostvol
           hostPath:
            path: /data